# Лучше перенести в другой файл
# file: ansible/setup.yml
- hosts: all
  tasks:
    - apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800 # 1 week

    - pip:
        name: docker
